# Generated by Django 5.2.16 on 2026-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='package',
            field=models.CharField(blank=True, choices=[('EXPRESS', 'Express'), ('STANDARD', 'Standard'), ('FULL_WEEK', 'Full week')], default='', max_length=20),
        ),
    ]
