# Generated by Django 5.2.16 on 2026-07-17 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weeklymenu',
            options={'ordering': [models.OrderBy(models.F('published_at'), descending=True, nulls_last=True)]},
        ),
    ]
