# Generated by Django 5.2.16 on 2026-07-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_weeklymenu_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='weeklymenu',
            constraint=models.CheckConstraint(condition=models.Q(('is_published', False), ('published_at__isnull', False), _connector='OR'), name='weeklymenu_published_at_set_when_published'),
        ),
    ]
